### ISSUE TITLE
LogExporter not Working with NewRelic 

### ISSUE THREAD

**Issue by BraunreutherA** [RichiCoder1/opentelemetry-sdk-workers#10]
Hey there 👋 

I tried to use the library with the native OTLP endpoint of New Relic and traces seem to work well so far. Still I don't get any logs in (even not as errored requests). Do you have any recommendation on how to test if it's a problem with New Relic or the log exporter  itself?

What OTLP Endpoint / service are you sending the data to?

**Comment by RichiCoder1** [comment]
By default, we're just sending via the standard OTLP/HTTP protocol, using the recently stabilized JSON encoding for both traces and logs. I've validated against the raw collector and Elastic Cloud. There's a non-zero chance that New Relic doesn't fully support the log protocol yet since it's newer.

**Comment by BraunreutherA** [comment]
The NR docs say OTLP/HTTP is supported and the traces are coming in. Can't say for sure if it supports the latest standard.

Can you share the setup how you got elastic cloud running? Also tried it yesterday sadly without success.

**Comment by RichiCoder1** [comment]
Ahhh, it looks like New Relic _currently_ only spports the v1.8.0 spec which predates the introduction of the log model: https://docs.newrelic.com/docs/more-integrations/open-source-telemetry-integrations/opentelemetry/opentelemetry-setup/#unsupported-specs

I should probably add this caveat to the README, but Log support across providers is basically non-existent. My specific setup for Elastic Cloud was:

* Standing up an Elastic Cloud cluster via https://www.elastic.co/pricing/. I used a standard cluster and turned all the defaults down to the bare minimum. An ECK cluster might worked, but I didn't try.
* I had to setup a proxy Otel Collector to translate OTLP HTTP/JSON to OTLP HTTP/ProtoBuf, as EC doesn't support JSON (yet). That said, I did later add native ProtoBuf support to this SDK, so you could go direct.
* Setup the SDK roughly following these instructions: https://www.elastic.co/guide/en/apm/guide/current/open-telemetry.html#instrument-apps-otel

That should get you logs and traces flowing into EC's APM feature!

**Comment by BraunreutherA** [comment]
Thanks for the explanation!

I've tried to get the native `OTLPProtoTraceExporter` & `OTLPProtoLogExporter` working with Elastic Cloud but sadly didn't succeed. There's always a timeout error from the exporter - that's a bit hard to debug what the problem could be. My config looks like this:

```ts
 const opentelemetry = new WorkersSDK(request, this.context, {
      service: (<typeof CloudflareWorkersService>this.constructor).SERVICE_NAME,
      logExporter: new OTLPProtoLogExporter({
        url: this.env.OTLP_ENDPOINT,
        headers: { 'Authorization': `Bearer ${this.env.OTLP_SECRET}` },
        timeoutMillis: 10000
      }),
      traceExporter: new OTLPProtoTraceExporter({
        url: this.env.OTLP_ENDPOINT,
        headers: { 'Authorization': `Bearer ${this.env.OTLP_SECRET}` },
        timeoutMillis: 10000
      }),
    });
```

Do you have any idea on this? 

As soon as I got something to work, I could start writing a tutorial on how to set it up.

**Comment by RichiCoder1** [comment]
That's odd 🤔. I'd double check that you're using the correct _APM_ specific endpoint, and also that there's no special network policy at play.

**Comment by BraunreutherA** [comment]
That's super strange - I've tried all apm URLs which I could find in elastic cloud. Maybe you could validate me: 

1. option: I went to: `https://<our-name>.kb.eu-central-1.aws.cloud.es.io:9243/app/home#/tutorial/apm` and copied the `serverUrl` from the nodejs apm agent config. Which looks like: `https://bc52694c46d547649a85e249dxxxxxx.apm.eu-central-1.aws.cloud.es.io:443`

2. option: I used the apm endpoint `https://<our-name>.apm.eu-central-1.aws.cloud.es.io` .

Couldn't find more - feeling a bit dumb already 😄

**Comment by RichiCoder1** [comment]
Nope, that looks correct! You've got basically the same configuration I had, though that timeout error sounds familiar. Let me double check what my setup was real quick.

**Comment by Sibirius** [comment]
Hey @BraunreutherA and me tried to get this working again with Elastic Cloud and added some logging into the library to see what errors we're getting.
This is the response we're getting from the APM when flushing:
```
Status: 400
\b\u0003\u0012\u0019proto: illegal wireType 7
```

Maybe this helps in narrowing down the issue.

**Comment by RichiCoder1** [comment]
That's odd, that means there's some sort of mismatch between the Log Proto we're using an what Elastic APM supports 🤔. I don't know why though, we're generating from the protos in the standard repo exactly like the official JS library does. Does this happen with just tracing?

**Comment by RichiCoder1** [comment]
I wonder also if it's not related to the compression we're doing. Currently this Lib unconditionally compresses outgoing traces: https://github.com/RichiCoder1/opentelemetry-sdk-workers/blob/main/packages/opentelemetry-sdk-workers/src/exporters/OTLPCloudflareExporterBase.ts#L101

I think the reason this might have been working from me is I was sending compressed traces to a collector, which then forwarded them on uncompressed to Elastic?

**Comment by Sibirius** [comment]
Hey thanks for the quick response! I have just removed the compression and now we're getting `200` from Elastic 🎉 
The logs now show up in elastic but the traces unfortunately don't. Even though it lists all our services and I can see the tracing data being sent.

**Comment by BraunreutherA** [comment]
Here is a PR which makes compression optional: https://github.com/RichiCoder1/opentelemetry-sdk-workers/pull/14
