### ISSUE TITLE
LogExporter should not log to console

### ISSUE THREAD

**Issue by BraunreutherA** [RichiCoder1/opentelemetry-sdk-workers#15]
Hey there 👋, 

when using any LogExporter and `sdk.log.log("Test Log!");` (comment: why is it `sdk.log` instead of `sdk.logger`?) then not only the log is sent to the OpenTelemetry endpoint but also logged to the console. This seems a bit off, as this should not be a concern of the build in logger. I know diary is used below this, so maybe this functionality could be disabled.

When somenbody wants the functionality of logging to console & otel, they should build a logger interface which accepts log sinks - e.x. the `sdk.log`

**Comment by RichiCoder1** [comment]
This was a convience/debugging thing so that consumers could still live tail their logs via the Cloudflare Interface. That said, I have no problem making this an Opt-in behavior.

Would also be good making `sdk.log` -> `sdk.logger`
