### ISSUE TITLE
Endpoint paths should be configurable

### ISSUE THREAD

**Issue by BraunreutherA** [RichiCoder1/opentelemetry-sdk-workers#16]
Hey there 👋 

the endpoint paths are fixed to `<my_otlp_url>/v1/traces` & `<my_otlp_url>/v1/logs like here: https://github.com/RichiCoder1/opentelemetry-sdk-workers/blob/main/packages/opentelemetry-sdk-workers/src/exporters/OTLPJsonTraceExporter.ts

There are services which don't follow this specs like: [Lightstep](https://lightstep.com/opentelemetry/js) -> `https://ingest.lightstep.com:443/api/v2/otel/trace` which makes it impossible to use the lib. 

That's why it should be possible to configure the full url or the paths in some way.

**Comment by RichiCoder1** [comment]
That makes sense! I'll get this change in (and the other one). Apologies for the delay, came down sick recently so only just getting back to projects.
